//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotGames.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiotGames.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}.
        /// </summary>
        internal static string CHAMPION_MASTERY_ALL_SUMMONER_ID {
            get {
                return ResourceManager.GetString("CHAMPION_MASTERY_ALL_SUMMONER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/champion-mastery/v4/scores/by-summoner/{encryptedSummonerId}.
        /// </summary>
        internal static string CHAMPION_MASTERY_SCORE_SUMMONER_ID {
            get {
                return ResourceManager.GetString("CHAMPION_MASTERY_SCORE_SUMMONER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}/by-champion/{championId}.
        /// </summary>
        internal static string CHAMPION_MASTERY_SUMMONER_CHAMPION_ID {
            get {
                return ResourceManager.GetString("CHAMPION_MASTERY_SUMMONER_CHAMPION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/platform/v3/champion-rotations.
        /// </summary>
        internal static string CHAMPION_ROTATION {
            get {
                return ResourceManager.GetString("CHAMPION_ROTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/league/v4/challengerleagues/by-queue/{queue}.
        /// </summary>
        internal static string LEAGUE_CHALLENGER_QUEUE {
            get {
                return ResourceManager.GetString("LEAGUE_CHALLENGER_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/league/v4/grandmasterleagues/by-queue/{queue}.
        /// </summary>
        internal static string LEAGUE_GRANDMASTER_QUEUE {
            get {
                return ResourceManager.GetString("LEAGUE_GRANDMASTER_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/league/v4/leagues/{leagueId}.
        /// </summary>
        internal static string LEAGUE_ID {
            get {
                return ResourceManager.GetString("LEAGUE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/league/v4/masterleagues/by-queue/{queue}.
        /// </summary>
        internal static string LEAGUE_MASTER_QUEUE {
            get {
                return ResourceManager.GetString("LEAGUE_MASTER_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/league/v4/entries/{queue}/{tier}/{division}.
        /// </summary>
        internal static string LEAGUE_QUEUE_TIER_DIVISION {
            get {
                return ResourceManager.GetString("LEAGUE_QUEUE_TIER_DIVISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/league/v4/entries/by-summoner/{encryptedSummonerId}.
        /// </summary>
        internal static string LEAGUE_SUMMONER_ID {
            get {
                return ResourceManager.GetString("LEAGUE_SUMMONER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/status/v3/shard-data.
        /// </summary>
        internal static string LOL_STATUS_SHARD {
            get {
                return ResourceManager.GetString("LOL_STATUS_SHARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/match/v4/matchlists/by-account/{encryptedAccountId}.
        /// </summary>
        internal static string MATCH_ALL_ACCOUNT_ID {
            get {
                return ResourceManager.GetString("MATCH_ALL_ACCOUNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/match/v4/matches/by-tournament-code/{tournamentCode}/ids.
        /// </summary>
        internal static string MATCH_ID_TOURNAMENT_CODE {
            get {
                return ResourceManager.GetString("MATCH_ID_TOURNAMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/match/v4/matches/{matchId}.
        /// </summary>
        internal static string MATCH_MATCH_ID {
            get {
                return ResourceManager.GetString("MATCH_MATCH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/match/v4/matches/{matchId}/by-tournament-code/{tournamentCode}.
        /// </summary>
        internal static string MATCH_MATCH_ID_TOURNAMENT_CODE {
            get {
                return ResourceManager.GetString("MATCH_MATCH_ID_TOURNAMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/match/v4/timelines/by-match/{matchId}.
        /// </summary>
        internal static string MATCH_TIMELINE_MATCH_ID {
            get {
                return ResourceManager.GetString("MATCH_TIMELINE_MATCH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/spectator/v4/featured-games.
        /// </summary>
        internal static string SPECTATOR_ALL_GAMES {
            get {
                return ResourceManager.GetString("SPECTATOR_ALL_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/spectator/v4/active-games/by-summoner/{encryptedSummonerId}.
        /// </summary>
        internal static string SPECTATOR_CURRENT_GAME_SUMMONER_ID {
            get {
                return ResourceManager.GetString("SPECTATOR_CURRENT_GAME_SUMMONER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/summoner/v4/summoners/by-account/{encryptedAccountId}.
        /// </summary>
        internal static string SUMMONER_ACCOUNT_ID {
            get {
                return ResourceManager.GetString("SUMMONER_ACCOUNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/summoner/v4/summoners/{encryptedSummonerId}.
        /// </summary>
        internal static string SUMMONER_ID {
            get {
                return ResourceManager.GetString("SUMMONER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/summoner/v4/summoners/by-name/{summonerName}.
        /// </summary>
        internal static string SUMMONER_NAME {
            get {
                return ResourceManager.GetString("SUMMONER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/summoner/v4/summoners/by-puuid/{encryptedPUUID}.
        /// </summary>
        internal static string SUMMONER_PUUID {
            get {
                return ResourceManager.GetString("SUMMONER_PUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/platform/v4/third-party-code/by-summoner/{encryptedSummonerId}.
        /// </summary>
        internal static string THIRD_PARTY_CODE_SUMMONER_ID {
            get {
                return ResourceManager.GetString("THIRD_PARTY_CODE_SUMMONER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament/v4/lobby-events/by-code/{tournamentCode}.
        /// </summary>
        internal static string TOURNAMENT_GET_LOBBY_EVENTS_TOURNAMENT_CODE {
            get {
                return ResourceManager.GetString("TOURNAMENT_GET_LOBBY_EVENTS_TOURNAMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament/v4/codes/{tournamentCode}.
        /// </summary>
        internal static string TOURNAMENT_GET_TOURNAMENT_CODE {
            get {
                return ResourceManager.GetString("TOURNAMENT_GET_TOURNAMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament/v4/providers.
        /// </summary>
        internal static string TOURNAMENT_POST_PROVIDER {
            get {
                return ResourceManager.GetString("TOURNAMENT_POST_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament/v4/codes.
        /// </summary>
        internal static string TOURNAMENT_POST_TOURNAMENT_CODE {
            get {
                return ResourceManager.GetString("TOURNAMENT_POST_TOURNAMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament/v4/codes/{tournamentCode}.
        /// </summary>
        internal static string TOURNAMENT_PUT_TOURNAMENT_CODE {
            get {
                return ResourceManager.GetString("TOURNAMENT_PUT_TOURNAMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament-stub/v4/codes.
        /// </summary>
        internal static string TOURNAMENT_STUB_CODE {
            get {
                return ResourceManager.GetString("TOURNAMENT_STUB_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament-stub/v4/providers.
        /// </summary>
        internal static string TOURNAMENT_STUB_PROVIDER {
            get {
                return ResourceManager.GetString("TOURNAMENT_STUB_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament-stub/v4/tournaments.
        /// </summary>
        internal static string TOURNAMENT_STUB_TOURNAMENT {
            get {
                return ResourceManager.GetString("TOURNAMENT_STUB_TOURNAMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lol/tournament-stub/v4/lobby-events/by-code/{tournamentCode}.
        /// </summary>
        internal static string TOURNAMENT_STUB_TOURNAMENT_CODE {
            get {
                return ResourceManager.GetString("TOURNAMENT_STUB_TOURNAMENT_CODE", resourceCulture);
            }
        }
    }
}
